"""
reporter.py — Generate severity-ranked Markdown reports and rich terminal output.
"""

from datetime import datetime
from reviewer import ChunkReview, ReviewIssue
from github_client import PRInfo


SEVERITY_ORDER = {"CRITICAL": 0, "WARNING": 1, "SUGGESTION": 2}
SEVERITY_EMOJI = {"CRITICAL": "🔴", "WARNING": "🟡", "SUGGESTION": "🔵"}
SEVERITY_BADGE = {
    "CRITICAL": "![CRITICAL](https://img.shields.io/badge/severity-CRITICAL-red)",
    "WARNING":  "![WARNING](https://img.shields.io/badge/severity-WARNING-yellow)",
    "SUGGESTION": "![SUGGESTION](https://img.shields.io/badge/severity-SUGGESTION-blue)",
}


def _sort_issues(issues: list[ReviewIssue]) -> list[ReviewIssue]:
    return sorted(issues, key=lambda i: SEVERITY_ORDER.get(i.severity, 99))


def _all_issues(reviews: list[ChunkReview]) -> list[ReviewIssue]:
    issues = []
    for r in reviews:
        issues.extend(r.issues)
    return _sort_issues(issues)


def generate_markdown(
    reviews: list[ChunkReview],
    source_label: str = "Code Review",
    pr_info: PRInfo | None = None,
    backend: str = "ollama",
    model: str = "",
) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    all_issues = _all_issues(reviews)

    counts = {"CRITICAL": 0, "WARNING": 0, "SUGGESTION": 0}
    for issue in all_issues:
        counts[issue.severity] = counts.get(issue.severity, 0) + 1

    lines: list[str] = []

    # Header
    lines.append(f"# 🛡️ CodeSentinel Report")
    lines.append(f"\n**Source:** `{source_label}`  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Backend:** {backend} / {model}  ")

    if pr_info:
        lines.append(f"\n## Pull Request")
        lines.append(f"- **Repo:** `{pr_info.repo}`")
        lines.append(f"- **PR #{pr_info.pr_number}:** {pr_info.title}")
        lines.append(f"- **Author:** @{pr_info.author}")
        lines.append(f"- **Branch:** `{pr_info.head_branch}` → `{pr_info.base_branch}`")
        lines.append(f"- **Changes:** +{pr_info.additions} / -{pr_info.deletions} across {pr_info.files_changed} files")

    # Summary
    lines.append(f"\n## Summary\n")
    lines.append(f"| Severity | Count |")
    lines.append(f"|---|---|")
    lines.append(f"| 🔴 CRITICAL | **{counts['CRITICAL']}** |")
    lines.append(f"| 🟡 WARNING  | **{counts['WARNING']}** |")
    lines.append(f"| 🔵 SUGGESTION | **{counts['SUGGESTION']}** |")
    lines.append(f"| **Total** | **{len(all_issues)}** |")

    if counts["CRITICAL"] > 0:
        lines.append(f"\n> ⚠️ **{counts['CRITICAL']} critical issue(s) require immediate attention before merging.**")

    # Issues by chunk
    lines.append(f"\n## Issues\n")

    if not all_issues:
        lines.append("✅ No issues found. Code looks clean!")
    else:
        chunk_map: dict[str, list[ReviewIssue]] = {}
        for issue in all_issues:
            chunk_map.setdefault(issue.chunk_name, []).append(issue)

        for chunk_name, issues in chunk_map.items():
            lines.append(f"### `{chunk_name}`\n")
            for i, issue in enumerate(issues, 1):
                emoji = SEVERITY_EMOJI.get(issue.severity, "⚪")
                lines.append(f"#### {emoji} {issue.severity} — {issue.title}")
                if issue.line_hint:
                    lines.append(f"*Line ~{issue.line_hint}*\n")
                lines.append(f"**Problem:** {issue.description}\n")
                lines.append(f"**Fix:** {issue.fix}\n")
                lines.append("---")

    # Errors
    errors = [(r.chunk.name, r.error) for r in reviews if r.error]
    if errors:
        lines.append(f"\n## ⚠️ Review Errors\n")
        for name, err in errors:
            lines.append(f"- `{name}`: {err}")

    # Chunks reviewed
    lines.append(f"\n## Chunks Reviewed\n")
    lines.append(f"| Chunk | Type | Lines | Issues |")
    lines.append(f"|---|---|---|---|")
    for r in reviews:
        c = r.chunk
        issue_count = len(r.issues)
        lines.append(f"| `{c.name}` | {c.chunk_type} | {c.start_line}–{c.end_line} | {issue_count} |")

    lines.append(f"\n---\n*Generated by [CodeSentinel](https://github.com/your/codesentinel)*")

    return "\n".join(lines)


def print_rich_summary(reviews: list[ChunkReview]) -> None:
    """Print a colored terminal summary using rich."""
    try:
        from rich.console import Console
        from rich.table import Table
        from rich import box
        console = Console()
    except ImportError:
        _print_plain_summary(reviews)
        return

    all_issues = _all_issues(reviews)
    counts = {"CRITICAL": 0, "WARNING": 0, "SUGGESTION": 0}
    for issue in all_issues:
        counts[issue.severity] = counts.get(issue.severity, 0) + 1

    console.print("\n[bold]🛡️  CodeSentinel Results[/bold]\n")

    # Summary table
    table = Table(box=box.ROUNDED, show_header=True, header_style="bold")
    table.add_column("Severity", style="bold")
    table.add_column("Count", justify="right")
    table.add_row("[red]🔴 CRITICAL[/red]", str(counts["CRITICAL"]))
    table.add_row("[yellow]🟡 WARNING[/yellow]", str(counts["WARNING"]))
    table.add_row("[blue]🔵 SUGGESTION[/blue]", str(counts["SUGGESTION"]))
    table.add_row("[bold]Total[/bold]", f"[bold]{len(all_issues)}[/bold]")
    console.print(table)

    if not all_issues:
        console.print("\n[green]✅ No issues found![/green]\n")
        return

    # Issue list
    console.print()
    for issue in all_issues:
        color = {"CRITICAL": "red", "WARNING": "yellow", "SUGGESTION": "blue"}.get(issue.severity, "white")
        emoji = SEVERITY_EMOJI.get(issue.severity, "⚪")
        line_info = f" (line ~{issue.line_hint})" if issue.line_hint else ""
        console.print(f"[{color}]{emoji} [{issue.severity}] {issue.title}[/{color}]{line_info}")
        console.print(f"  [dim]Chunk:[/dim] {issue.chunk_name}")
        console.print(f"  [dim]Problem:[/dim] {issue.description}")
        console.print(f"  [dim]Fix:[/dim] {issue.fix}")
        console.print()


def _print_plain_summary(reviews: list[ChunkReview]) -> None:
    all_issues = _all_issues(reviews)
    print(f"\n=== CodeSentinel Results ===")
    print(f"Total issues: {len(all_issues)}")
    for issue in all_issues:
        emoji = SEVERITY_EMOJI.get(issue.severity, "•")
        line_info = f" (line ~{issue.line_hint})" if issue.line_hint else ""
        print(f"\n{emoji} [{issue.severity}] {issue.title}{line_info}")
        print(f"  Chunk: {issue.chunk_name}")
        print(f"  Problem: {issue.description}")
        print(f"  Fix: {issue.fix}")
    print()